[mypy]
warn_unused_configs = True
explicit_package_bases = True
disable_error_code = annotation-unchecked

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-instanseg.*]
ignore_missing_imports = True

[mypy-sahi.*]
ignore_missing_imports = True

[mypy-tiffile.*]
ignore_missing_imports = True

[mypy-csbdeep.*]
ignore_missing_imports = True

[mypy-ultralytics.*]
ignore_missing_imports = True

[mypy-cellpose.*]
ignore_missing_imports = True

[mypy-stardist.*]
ignore_missing_imports = True
